-- NDiplomacy
NDefines.NDiplomacy.TRUCE_YEARS = 5
NDefines.NDiplomacy.SCALED_TRUCE_YEARS = 10
NDefines.NDiplomacy.COALITION_YEARS = 20

-- NCountry
NDefines.NCountry.ABANDON_IDEAGROUP_REFUND = 0.25
NDefines.NCountry.ADVISOR_COST_INCREASE_PER_YEAR = 0.01
NDefines.NCountry.BASE_MP_TO_MANPOWER = 0.2
NDefines.NCountry.BASE_POSSIBLE_POLICIES = 4
NDefines.NCountry.FREE_IDEA_GROUP_COST  = 4
NDefines.NCountry.IDEA_TO_TECH = -0.01
NDefines.NCountry.INNOVATIVENESS_FIRST_PICKED_IDEA = 1.0
NDefines.NCountry.MAX_ACTIVE_POLICIES = 9
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.5
NDefines.NCountry.POWER_MAX = 2499
NDefines.NCountry.PS_BUY_IDEA = 300
NDefines.NCountry.MAX_EXTRA_PERSONALITIES = 3
NDefines.NCountry.FIRST_EXTRA_PERSONALITY = 5
NDefines.NCountry.YEARS_PER_EXTRA_PERSONALITY = 10

-- NEconomy
NDefines.NEconomy.BASE_INTERESTS = 5.0
NDefines.NEconomy.EDICTS_COST_INCREASE = 1.0
NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.10